services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    secrets:
      - db-password
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eventManager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db-password
    networks:
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: eventManager
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    networks:
      - spring-mysql
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
secrets:
  db-password:
    file: db/password.text
networks:
  spring-mysql:
    driver: bridge